server:
  port: 8080
  mode: dev

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbname: test
  conf: charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 151                 # 最大连接数
  maxOpenConns: 151                 # 最大打开连接数
  vonnMaxLifetime : 3600            # 设置可以重用连接的最大时间量 （秒）
  logpath: ./mysqllog/

redis:
  host: 127.0.0.1
  port: 6379
  username: root
  password:
  MaxIdle: 5         # 最大的空闲连接数，表示即使没有redis连接时依然可以保持N个空闲的连接，而不被清除，随时处于待命状态。
  MaxActive: 30      # 最大的激活连接数，表示同时最多有N个连接
  IdleTimeout: 300    # 最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭 （秒）

log:
  path: ./log/   # 日志输出位置
  rotateDays: 7    #定期清理日志文件（天）
  rotateSize: 100    #日志文件分片存储大小（MB）
  backups: 100    #日志文件分片存储数量

upload:
  path: ./file/  # 文件上传位置

